config/routes.rb
Roots::Application.routes.draw do

  get "cajas/cajas"
  get "cajas/create"
 concern :globales do
    collection do
      post :borrar_seleccion
      get :editar_multiples
      put :actualizar_multiples
      post :importar
    end
  end

  get 'salir', to: 'rba/sesiones#salir', :as => :salir
  get '/api/rba/sesiones/salir', to: 'api/rba/sesiones#salir'
  get '/rba/sesiones/actualizaSesion/:modelo/:id', to: 'rba/sesiones#actualizaSesion', :as => :actualizaSesion
  post 'rba/mover_items', to: 'rba/nodos#mover_items'
  root 'rba/bienvenidos#inicio'
  
  namespace :rad do
    resources :operaciones do
      post :compatibles, on: :collection
      get :compatibles, on: :member
      concerns [:globales]
    end
    resources :operaciontipos,
    concerns: [:globales]

  end
  namespace :rfi do
    resources :flujofondos
  end
  namespace :rba do
    resources :actividades,
    :actividadtipos, 
    :arboles, 
    :campanas, 
    :campanatipos, 
    :catfiscales, 
    :empresagrupos, 
    :empresas,
    :establecimientos, 
    :libros,
    :lotes, 
    :loteutilizaciones,
    :nodos, 
    :organizaciontipos,
    :organizaciones,
    :temporadas,
    :usuarios,
    concerns: [:globales]
    resources :sesiones
  end

  namespace :rco do
    resources :cuentas do
      post :x_operacion_tipo, on: :collection
      concerns [:globales]
    end
    resources :cuentatipos,
    :registros, 
    :asientos, 
    :cotizaciones,
    :monedas,
    concerns: [:globales]
    resources :eerrs
  end

  namespace :rga do
    resources :categorias,
    :categoriatipos,
    :estados,
    :estados_eventos,
    :eventotipos,
    :rodeos,
    concerns: [:globales]
    resources :animales do
      post :disponibles, on: :collection
      concerns [:globales]
    end

    resources :registros do
      get :planilla, on: :collection
      get :existencia, on: :collection
      concerns [:globales]
    end
  
    resources :eventos do
      get :actualizar_categorias, on: :member
      get :actualizar_estados, on: :member
      concerns [:globales]
    end
  end

    namespace :api, defaults: {format: 'json'} do
      namespace :rba do
        resources :sesiones
        resources :cajas do
          get :caja, on: :collection
          get :egresos, on: :collection
        end
      end
    end

end

app/controllers/rfi/flujofondos_controller.rb
class Rfi::FlujofondosController < ApplicationController
	
	def index
		empresaGrupoId = session[:empresagrupo_id]
		empresaId = session[:empresa_id]
		hoy = Date.today
		@rep = 8 
		tiposDeCuenta = [1.12,1.2,1.9,2.2,2.9,2.1]
		fin = hoy.advance(:months => @rep - 2) 
		hasta = Date.new(fin.year,fin.month, -1)
		ctasAlInicio = Rco::Cuenta.conSaldo(tiposDeCuenta,hoy,empresaGrupoId)
		ctasAlFin = Rco::Cuenta.conSaldo(tiposDeCuenta,hasta,empresaGrupoId)
		@ctasDisp = ctasAlInicio | ctasAlFin
		@ctasDisp.sort! { |a,b| a.cuentatipo_codigo <=> b.cuentatipo_codigo }
		ctasDispIds = @ctasDisp.collect(&:id)
		@sDI = Rco::Registro.saldoCta(ctasDispIds,hoy,empresaId) # saldos iniciales
		sDI = Array.new
		@sDI.each {|k,v| sDI.push(v)}
		@sDITotal = sDI.sum.round(2)

		@sDF = Rco::Registro.saldoCta(ctasDispIds,hasta,empresaId) # saldos finales 
		sDF = Array.new
		@sDF.each {|k,v| sDF.push(v)}
		@sDFTotal = sDF.sum.round(2)
		@sMes = Array.new	
		@sMesTotales = Array.new
		@rep.times do |t|
			sMes = Array.new
			if t == 0
				@sMes[t] = Rco::Registro.saldoPeriodoCta(ctasDispIds,hoy,Date.today.end_of_month,empresaId)
			else	
				@sMes[t] = Rco::Registro.saldoMesCta(ctasDispIds,hoy.advance(:months => t),empresaId)
			end
			@sMes[t].each {|k,v| sMes.push(v)} 
			@sMesTotales[t] = sMes.sum.round(2)

		end
		@meses = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre']
		respond_to do |format|
			format.html

		end


	end
end

app/helpers/rfi/flujofondos_helper.rb
module Rfi::FlujofondosHelper
end

app/views/rfi/flujofondos/index.html.erb
 <div class="panel">
<div class="row" data-no-turbolink>
<% @rep -= 1%>
<table class="notDT">
	<thead>
		<th>CUENTAS</th>
		<th>SI</th>
		<% @rep.times do |t| %>
			<th><%= @meses[Date.today().advance(:months => t).month.to_i - 1] %></th>
	<% end %>
		<th>SF</th>
	</thead>
	<tbody>
		<tr>
			<td class="acumulado">SALDO MES</td>
			<td class="acumulado">--</td>
			<% acumulados = @sDITotal  %>
			<% @rep.times do |t| %>
				<% acumulados += @sMesTotales[t]  %>
				<td class="acumulado"><%= acumulados.round(2) %></td>
			<% end %>
			<td class="acumulado">--</td>
		</tr>	
		<%	@ctasDisp.each do |cd| %>
			<tr>
				<td><%= cd.nombre %></td> 
				<td><%= link_to @sDI[cd.id].to_s, rco_registros_path(:desde => '2010-01-01', :hasta => Date.today, :cuentas => cd.id, :ver_saldos => 1)  %></td>
				<% @rep.times do |t| %>
					<% if t == 0 %>
					<% fd = Date.today.advance(:days => 1) %>
					<%else%>
						<% fd = Date.new(Date.today.year,Date.today.month,1).advance(:months => t) %>
						<%end%>
					<% fh = Date.new(Date.today.year,Date.today.month,-1).advance(:months => t) %>
					<td><%= link_to @sMes[t][cd.id].to_s, rco_registros_path(:desde => fd, :hasta => fh, :cuentas => cd.id, :ver_saldos => 1) %></td>
				<% end %>
				<td><%= @sDF[cd.id] %></td>
			</tr>
		<% end %>
		<tr>
			<td>TOTAL</td>
			<td><%= link_to @sDITotal.to_s, rco_registros_path(:desde =>'2010-01-01', :hasta =>Date.today, :ver_saldos => 1) %></td>
			<% @rep.times do |t| %>
				<% if t == 0 %>
					<% fd = Date.today.advance(:days => 1) %>
				<%else%>
					<% fd = Date.new(Date.today.year,Date.today.month,1).advance(:months => t) %>
				<%end%>
				<% fh = Date.new(Date.today.year,Date.today.month,-1).advance(:months => t) %>
				<td><%= link_to @sMesTotales[t].to_s, rco_registros_path(:desde => fd, :hasta => fh, :cuentas => @ctasDisp.collect(&:id), :ver_saldos => 1) %></td>
			<%end%>
			<td><%= @sDFTotal %></td>
		</tr>


	</tbody>
</table>

</div>
</div>